const $=id=>document.getElementById(id);
let stream=null,type=null,idVerified=false,idImage="";
let records=JSON.parse(localStorage.getItem("customer_records")||"[]");

async function openCam(t){type=t;$("camTitle").textContent={id:"Scan Any ID Card",engine:"Scan Engine Number",chassis:"Scan Chassis Number",g:"Scan Guarantor ID"}[t];$("camMsg").textContent={id:"Scan the original ID card clearly.",engine:"Place SSE engine number inside the frame.",chassis:"Place SAC chassis number inside the frame.",g:"Scan guarantor's original ID card."}[t];$("modal").classList.add("open");try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1920},height:{ideal:1080}},audio:false});$("video").srcObject=stream}catch(e){closeCam();toast("Camera unavailable. Upload an image instead.");({id:"idFile",engine:"engineFile",chassis:"chassisFile",g:"gFile"}[t]&&$( {"id":"idFile","engine":"engineFile","chassis":"chassisFile","g":"gFile"}[t]).click())}}
function closeCam(){if(stream){stream.getTracks().forEach(x=>x.stop());stream=null}$("video").srcObject=null;$("modal").classList.remove("open")}
async function capture(){let v=$("video");if(!v.videoWidth)return toast("Camera is not ready.");let c=document.createElement("canvas");c.width=v.videoWidth;c.height=v.videoHeight;c.getContext("2d").drawImage(v,0,0,c.width,c.height);let data=c.toDataURL("image/jpeg",.92);c.toBlob(async b=>{closeCam();let f=new File([b],"scan.jpg",{type:"image/jpeg"});if(type==="id"){idImage=data;$("idPreview").src=data;$("idPreviewBox").style.display="block";if(!await detectID(f)){idVerified=false;return toast("ID card not detected.")}await scanID(f)}else if(type==="g")await scanG(f);else await scanVehicle(f,type)},"image/jpeg",.92)}
async function detectID(file){try{let r=await Tesseract.recognize(file,"eng");let t=r.data.text.replace(/\s+/g," ").toUpperCase(),score=0;if(/\b[A-Z0-9]{5,20}[-\/]?[A-Z0-9]{2,20}\b/.test(t))score++;["IDENTITY","IDENTIFICATION","ID CARD","IDENTITY CARD","NATIONAL ID","PASSPORT","DATE OF BIRTH","DOB","BIRTH","SEX","GENDER","NAME","SURNAME","FATHER","MOTHER","COUNTRY","NATIONAL","DOCUMENT NO","DOCUMENT NUMBER","CARD NO","CARD NUMBER","EXPIRY","ISSUE DATE"].forEach(x=>{if(t.includes(x))score++});let ok=score>=3;$("idStatus").textContent=ok?"✓ ID card detected":"❌ ID card not detected";return ok}catch(e){return false}}
async function scanID(file){let r=await Tesseract.recognize(file,"eng"),t=r.data.text;let nm=t.match(/(?:FULL\s*NAME|NAME|SURNAME|GIVEN\s*NAME|NAMA)\s*[:\-]?\s*([A-Za-z][A-Za-z .'-]{2,60})/i),id=findID(t);if(nm)$("customerName").value=clean(nm[1]);if(id)$("nic").value=id;if(nm||id){idVerified=true;$("idStatus").textContent="✓ ID verified — check details"}else{idVerified=false;$("idStatus").textContent="⚠ ID detected but text unclear"}update()}
function findID(t){for(let p of [/\b\d{5}[- ]?\d{7}[- ]?\d\b/,/\b[A-Z]{1,3}\d{5,15}\b/i,/\b[A-Z0-9]{6,20}[-\/]?[A-Z0-9]{2,20}\b/i,/\b\d{6,20}\b/]){let m=t.match(p);if(m)return m[0].trim()}return""}
function clean(x){return x.replace(/[^A-Za-z .'-]/g,"").replace(/\s+/g," ").trim()}
async function scanVehicle(file,t){$("vehicleStatus").textContent="Scanning...";let r=await Tesseract.recognize(file,"eng"),s=r.data.text.toUpperCase().replace(/\s+/g," ");if(t==="engine"){let m=s.match(/SSE[\s:-]*[A-Z0-9-]{3,30}/);if(m)$("engine").value=m[0].replace(/\s+/g,"")}else{let m=s.match(/SAC[\s:-]*[A-Z0-9-]{3,30}/);if(m)$("chassis").value=m[0].replace(/\s+/g,"")}$("vehicleStatus").textContent="✓ Scan complete";update()}
async function scanG(file){$("gStatus").textContent="Scanning...";let r=await Tesseract.recognize(file,"eng"),t=r.data.text,n=t.match(/(?:FULL\s*NAME|NAME|SURNAME|NAMA)\s*[:\-]?\s*([A-Za-z][A-Za-z .'-]{2,60})/i),i=findID(t);if(n)$("gName").value=clean(n[1]);if(i)$("gNic").value=i;$("gStatus").textContent="✓ Scan complete";update()}
async function processID(f){let r=await detectID(f);if(!r){idVerified=false;return toast("ID card not detected.")}await scanID(f)}
$("idFile").onchange=e=>{let f=e.target.files[0];if(!f)return;let rd=new FileReader();rd.onload=()=>{$("idPreview").src=rd.result;idImage=rd.result;$("idPreviewBox").style.display="block"};rd.readAsDataURL(f);processID(f)}
$("engineFile").onchange=e=>e.target.files[0]&&scanVehicle(e.target.files[0],"engine");$("chassisFile").onchange=e=>e.target.files[0]&&scanVehicle(e.target.files[0],"chassis");$("gFile").onchange=e=>e.target.files[0]&&scanG(e.target.files[0]);
function update(){let total=+$("total").value||0,adv=+$("advance").value||0,b=Math.max(total-adv,0);$("balance").textContent=b.toLocaleString();$("pName").textContent=$("customerName").value||"—";$("pPhone").textContent=$("phone").value||"—";$("pId").textContent=$("nic").value||"—";$("pEngine").textContent=$("engine").value||"—";$("pChassis").textContent=$("chassis").value||"—";$("pGName").textContent=$("gName").value||"—";$("pGId").textContent=$("gNic").value||"—";$("pGPhone").textContent=$("gPhone").value||"—";$("pTotal").textContent=total.toLocaleString();$("pAdvance").textContent=adv.toLocaleString();$("pBalance").textContent=b.toLocaleString();$("date").textContent=new Date().toLocaleString();if(idImage){$("entryId").src=idImage;$("entryId").style.display="block"}}
["total","advance","customerName","phone","nic","engine","chassis","gName","gPhone","gNic"].forEach(x=>$(x).addEventListener("input",update));
$("scanId").onclick=()=>openCam("id");$("scanEngine").onclick=()=>openCam("engine");$("scanChassis").onclick=()=>openCam("chassis");$("scanG").onclick=()=>openCam("g");$("uploadId").onclick=()=>$("idFile").click();$("capture").onclick=capture;$("close").onclick=closeCam;
$("save").onclick=()=>{if(!idVerified)return toast("Scan and verify the customer ID first.");if(!$("customerName").value)return toast("Customer name is required.");let total=+$("total").value||0,adv=+$("advance").value||0;records.push({name:$("customerName").value,phone:$("phone").value,nic:$("nic").value,engine:$("engine").value,chassis:$("chassis").value,gName:$("gName").value,gPhone:$("gPhone").value,gNic:$("gNic").value,total,advance:adv,balance:Math.max(total-adv,0),idImage,createdAt:new Date().toISOString()});localStorage.setItem("customer_records",JSON.stringify(records));toast("✓ Entry saved")};
$("download").onclick=async()=>{if(!idVerified)return toast("Verify ID first.");update();let c=await html2canvas($("entry"),{scale:2,backgroundColor:"#fff",useCORS:true});let a=document.createElement("a");a.download="customer-entry-"+Date.now()+".png";a.href=c.toDataURL("image/png");a.click()};
$("csv").onclick=()=>{if(!records.length)return toast("No records.");let h=["Name","Phone","ID","Engine","Chassis","Guarantor","Guarantor Phone","Guarantor ID","Total","Advance","Balance","Date"],rows=records.map(r=>[r.name,r.phone,r.nic,r.engine,r.chassis,r.gName,r.gPhone,r.gNic,r.total,r.advance,r.balance,r.createdAt]),csv=[h,...rows].map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="customer-records.csv";a.click()};
function toast(x){let t=$("toast");t.textContent=x;t.style.display="block";clearTimeout(window.tt);window.tt=setTimeout(()=>t.style.display="none",3500)}update();